"""Initial migration

Revision ID: 2063a0b92f3c
Revises: 
Create Date: 2023-01-04 13:24:14.622320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2063a0b92f3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'empl_list_gas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fio', sa.String(length=128), nullable=True),
        sa.Column('tab_no', sa.String(length=128), nullable=True),
        sa.Column('depts', sa.String(length=256), nullable=True),
        sa.Column('post', sa.String(length=256), nullable=True),
        sa.Column('post_dop', sa.String(length=256), nullable=True),
        sa.Column('date_recr', sa.DateTime(), nullable=True),
        sa.Column('date_post', sa.DateTime(), nullable=True),
        sa.Column('sx', sa.String(length=16), nullable=True),
        sa.Column('date_birth', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hw_statuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('status_name', sa.String(length=64), nullable=True),
        sa.Column('status_name_ru', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hw_types',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('hw_type', sa.String(length=64), nullable=True),
        sa.Column('hw_type_ru', sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'maintenance_db',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('doc_id', sa.Integer(), nullable=True),
        sa.Column('hw_unit_id', sa.Integer(), nullable=True),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_docs_db',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('num_thru_year', sa.Integer(), nullable=True),
        sa.Column('doc_date', sa.DateTime(), nullable=True),
        sa.Column('doc_num', sa.String(length=16), nullable=True),
        sa.Column('units_qty', sa.Integer(), nullable=True),
        sa.Column('units_id_list', sa.String(length=2048), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'hw_db',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('invnum', sa.String(length=12), nullable=True),
        sa.Column('type_id', sa.Integer(), nullable=True),
        sa.Column('legacy_user', sa.String(length=50), nullable=True),
        sa.Column('empl_id', sa.Integer(), nullable=True),
        sa.Column('location', sa.String(length=4), nullable=True),
        sa.Column('status_id', sa.Integer(), nullable=True),
        sa.Column('manuf', sa.String(length=20), nullable=True),
        sa.Column('model', sa.String(length=64), nullable=True),
        sa.Column('vendor_id', sa.Integer(), nullable=True),
        sa.Column('serialnum', sa.String(length=64), nullable=True),
        sa.Column('year', sa.Integer(), nullable=True),
        sa.Column('warranty', sa.Integer(), nullable=True),
        sa.Column('accounting', sa.DateTime(), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('buhtext', sa.String(length=80), nullable=True),
        sa.Column('buh_os', sa.Integer(), nullable=True),
        sa.Column('check', sa.Integer(), nullable=True),
        sa.Column('gas_id', sa.Integer(), nullable=True),
        sa.Column('last_maintenance_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(('empl_id',), ('empl_list_gas.id',), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('last_maintenance_id',), ('maintenance_docs_db.id',), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('status_id',), ('hw_statuses.id',), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(('type_id',), ('hw_types.id',), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hw_db')
    op.drop_table('maintenance_docs_db')
    op.drop_table('maintenance_db')
    op.drop_table('hw_types')
    op.drop_table('hw_statuses')
    op.drop_table('empl_list_gas')
    # ### end Alembic commands ###
