"""Add Tomsk hardware type field

Revision ID: 294342e18357
Revises: eb1e72726e00
Create Date: 2025-02-09 16:40:47.638071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294342e18357'
down_revision = 'eb1e72726e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hw_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hw_type_tomsk', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hw_types', schema=None) as batch_op:
        batch_op.drop_column('hw_type_tomsk')

    # ### end Alembic commands ###
