"""Add sensors_log

Revision ID: 3b3c2d454d0b
Revises: 2063a0b92f3c
Create Date: 2023-03-05 00:51:11.102957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3c2d454d0b'
down_revision = '2063a0b92f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors_log',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('timestamp_utc', sa.DateTime(), nullable=True),
        sa.Column('sensor_id', sa.Integer(), nullable=True),
        sa.Column('sensor_tag', sa.String(length=32), nullable=True),
        sa.Column('sensor_value_string', sa.String(length=128), nullable=True),
        sa.Column('sensor_value_float', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors_log')
    # ### end Alembic commands ###
