"""Add ticket model

Revision ID: 8c77f86bf2ce
Revises: 9f9e0aa9b693
Create Date: 2023-07-15 13:29:17.991412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c77f86bf2ce'
down_revision = '9f9e0aa9b693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('unit_id', sa.BigInteger(), nullable=True),
                    sa.Column('status_id', sa.Integer(), nullable=True),
                    sa.Column('docs_status_id', sa.Integer(), nullable=True),
                    sa.Column('subj', sa.String(length=80), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('reason', sa.String(length=80), nullable=True),
                    sa.Column('needs_to_be_done', sa.String(length=120), nullable=True),
                    sa.Column('comleted_work', sa.String(length=160), nullable=True),
                    sa.Column('is_hotline', sa.Boolean(), nullable=True),
                    sa.Column('hotline_ticket_no', sa.BigInteger(), nullable=True),
                    sa.Column('hotline_ticket_date', sa.DateTime(), nullable=True),
                    sa.Column('hotline_ticket_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('hotline_fetch_date', sa.DateTime(), nullable=True),
                    sa.Column('iac_ticket_no', sa.BigInteger(), nullable=True),
                    sa.Column('ticket_comments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    # ### end Alembic commands ###
