"""Expand invnum field

Revision ID: 9f9e0aa9b693
Revises: 3b3c2d454d0b
Create Date: 2023-05-19 22:55:08.750964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9e0aa9b693'
down_revision = '3b3c2d454d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hw_db', schema=None) as batch_op:
        batch_op.alter_column('invnum',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hw_db', schema=None) as batch_op:
        batch_op.alter_column('invnum',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
