"""Add new maintenance

Revision ID: a2118b4b1ddb
Revises: 294342e18357
Create Date: 2025-04-27 18:03:23.372701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2118b4b1ddb'
down_revision = '294342e18357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'maintenance_docs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('quarter', sa.Integer(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('doc_date', sa.DateTime(), nullable=False),
        sa.Column('planned_units_qty', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'maintenance_records',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('hw_id', sa.BigInteger(), nullable=False),
        sa.Column('doc_id', sa.BigInteger(), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['doc_id'], ['maintenance_docs.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['hw_id'], ['hw_db.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_records')
    op.drop_table('maintenance_docs')
    # ### end Alembic commands ###
