"""Increase ticket fields size

Revision ID: c0a1f75fc50f
Revises: 8c77f86bf2ce
Create Date: 2024-03-11 21:19:28.701687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a1f75fc50f'
down_revision = '8c77f86bf2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('subj',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=160),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=160),
               existing_nullable=True)
        batch_op.alter_column('needs_to_be_done',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=160),
               existing_nullable=True)
        batch_op.alter_column('comleted_work',
               existing_type=sa.VARCHAR(length=160),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('comleted_work',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=160),
               existing_nullable=True)
        batch_op.alter_column('needs_to_be_done',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
        batch_op.alter_column('subj',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
