"""Add Tomsk hardware models table

Revision ID: eb1e72726e00
Revises: c0a1f75fc50f
Create Date: 2025-02-09 00:35:33.718805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1e72726e00'
down_revision = 'c0a1f75fc50f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hw_tomsk_models',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('line_num', sa.Integer(), nullable=True),
                    sa.Column('hw_type', sa.String(length=128), nullable=True),
                    sa.Column('manuf', sa.String(length=128), nullable=True),
                    sa.Column('model', sa.String(length=128), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hw_tomsk_models')
    # ### end Alembic commands ###
